config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: { sessions: "usuarios/sessions" }

  root to: 'clases#index'
  resources :clases
  resources :asignaturas
  resources :patron_clases
  post 'patron_clases/edicion_multiple' => 'patron_clases#edicion_multiple'
  get 'asignaturas/nuevo_patron/:id' => 'asignaturas#nuevo_patron'
end

app/models/asignatura.rb
class Asignatura < ActiveRecord::Base
	has_many :patron_clases, dependent: :destroy
	has_many :clases, through: :patron_clases

	has_many :patron_asignaturas
	has_many :programas, through: :patron_asignaturas

	has_many :datos_calendarios
	has_many :calendarios, through: :datos_calendarios

	scope :search, ->(keyword){ where('keywords LIKE?',"%#{keyword.downcase}%") if keyword.present?}

	before_save :generar_keywords

	protected
		def generar_keywords
			self.keywords = [nombre,descripcion,tags].map(&:downcase).join(' ')
		end
end

app/models/calendario.rb
class Calendario < ActiveRecord::Base
	has_many :datos_calendarios
	has_many :asignaturas, through: :datos_calendarios

	has_many :clases, through: :datos_calendarios

	belongs_to :programa
	belongs_to :descanso
end

app/models/clase.rb
class Clase < ActiveRecord::Base
	has_many :patron_clases, dependent: :destroy
	has_many :asignaturas, through: :patron_clases

	has_many :datos_calendarios
	has_many :calendarios, through: :datos_calendarios

	scope :search, ->(keyword){ where('keywords LIKE?',"%#{keyword.downcase}%") if keyword.present?}

	before_save :generar_keywords

	protected
		def generar_keywords
			self.keywords = [nombre,descripcion,recursos,tags].map(&:downcase).join(' ')
		end
end

app/models/datos_calendario.rb
class DatosCalendario < ActiveRecord::Base
	belongs_to :asignatura
	belongs_to :calendario
	belongs_to :clase
end

app/models/descanso.rb
class Descanso < ActiveRecord::Base
	has_many :calendarios
	
	has_many :patron_descansos
	has_many :pausas, through: :patron_descansos
end

app/models/patron_asignatura.rb
class PatronAsignatura < ActiveRecord::Base
	belongs_to :asignatura
	belongs_to :programa
end

app/models/patron_clase.rb
class PatronClase < ActiveRecord::Base
	belongs_to :asignatura
	belongs_to :clase
end
#TODO: Revisar que la eliminación de asignaturas o clases destruya las relaciones existentes.

app/models/patron_descanso.rb
class PatronDescanso < ActiveRecord::Base
	belongs_to :descanso
	belongs_to :pausa
end

app/models/pausa.rb
class Pausa < ActiveRecord::Base
	has_many :patron_descansos
	has_many :descansos, through: :patron_descansos
end

app/models/programa.rb
class Programa < ActiveRecord::Base
	has_many :patron_asignaturas
	has_many :asignaturas, through: :patron_asignaturas

	has_many :calendarios
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/asignaturas_controller.rb
# coding: utf-8
class AsignaturasController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_asignatura, only: [:update, :destroy]
  before_action :set_asignatura_patron, only: [:show, :edit]

  # GET /asignaturas
  # GET /asignaturas.json
  def index
    @asignaturas = Asignatura.search(params[:busqueda]).order(:nombre).page(params[:page]).per(20)
  end

  # GET /asignaturas/1
  # GET /asignaturas/1.json
  def show
  end

  # GET /asignaturas/new
  def new
    @asignatura = Asignatura.new
  end

  # GET /asignaturas/1/edit
  def edit
    @clases = Clase.search(params[:busqueda]).order(:nombre).page(params[:page]).per(10)
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /asignaturas
  # POST /asignaturas.json
  def create
    @asignatura = Asignatura.new(asignatura_params)

    respond_to do |format|
      if @asignatura.save
        format.html { redirect_to @asignatura, notice: 'La asignatura se ha creado con éxito.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /asignaturas/1
  # PATCH/PUT /asignaturas/1.json
  def update
    respond_to do |format|
      if @asignatura.update(asignatura_params)
        format.html { redirect_to @asignatura, notice: 'La asignatura se ha editado con éxito.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /asignaturas/1
  # DELETE /asignaturas/1.json
  def destroy
    @asignatura.destroy
    respond_to do |format|
      format.html { redirect_to asignaturas_url, notice: 'La asignatura se ha eliminado con éxito.' }
    end
  end

  def nuevo_patron
    @clase=params[:id]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asignatura
      @asignatura = Asignatura.find(params[:id])
    end
    def set_asignatura_patron
      @asignatura = Asignatura.includes(:patron_clases,:clases).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asignatura_params
      params.require(:asignatura).permit(:nombre, :descripcion, :tags)
    end
end

app/controllers/clases_controller.rb
# coding: utf-8
class ClasesController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_clase, only: [:show, :edit, :update, :destroy]

  # GET /clases
  # GET /clases.json
  def index
    @clases = Clase.search(params[:busqueda]).order(:nombre).page(params[:page]).per(30)
  end

  # GET /clases/1
  # GET /clases/1.json
  def show
  end

  # GET /clases/new
  def new
    @clase = Clase.new
  end

  # GET /clases/1/edit
  def edit
  end

  # POST /clases
  # POST /clases.json
  def create
    @clase = Clase.new(clase_params)

    respond_to do |format|
      if @clase.save
        format.html { redirect_to @clase, notice: 'La clase se ha creado con éxito.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /clases/1
  # PATCH/PUT /clases/1.json
  def update
    respond_to do |format|
      if @clase.update(clase_params)
        format.html { redirect_to @clase, notice: 'La clase se ha editado con éxito.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /clases/1
  # DELETE /clases/1.json
  def destroy
    @clase.destroy
    respond_to do |format|
      format.html { redirect_to clases_url, notice: 'La clase se ha eliminado con éxito.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clase
      @clase = Clase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clase_params
      params.require(:clase).permit(:nombre, :descripcion, :recursos, :tags)
    end
end

app/controllers/descansos_controller.rb
class DescansosController < ApplicationController
end

app/controllers/pausas_controller.rb
class PausasController < ApplicationController
end

app/controllers/programas_controller.rb
class ProgramasController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/helpers/calendarios_helper.rb
module CalendariosHelper
end

app/helpers/clases_helper.rb
module ClasesHelper
end

app/helpers/descansos_helper.rb
module DescansosHelper
end

app/helpers/pausas_helper.rb
module PausasHelper
end

app/helpers/programas_helper.rb
module ProgramasHelper
end

app/views/asignaturas/_asignatura.html.erb
<%= content_tag_for(:tr, asignatura) do %>
	<td><%= link_to asignatura.nombre, asignatura %></td>
	<td><%= asignatura.descripcion %></td>
	<td><% tags = asignatura.tags.split(",") %>
		<% tags.each do |tag| %>
		<%# Añadir link a búsqueda por ese tag %>
		<span class="label label-info"><%= tag.strip %></span>
		<% end %>
	</td>
	<td><%= link_to '', edit_asignatura_path(asignatura), class: "glyphicon glyphicon-cog", title: "Editar" %>
		<%= link_to '', asignatura, method: :delete, data: { confirm: '¿Estás seguro?' }, class: "glyphicon glyphicon-trash", title: "Eliminar" %>
	</td>
<% end %>

app/views/asignaturas/_edicion_patron_clase.html.erb
<%
	unless defined? patron
		patron = PatronClase.new() 
		patron.duracion = 1
		patron.orden = 99
		patron.clase = Clase.find(@clase)
	end
%>
<%= content_tag_for(:li, patron, class: "list-group-item", data: {duracion:patron.duracion, orden: patron.orden, clase: patron.clase.id}) do %>
	<%= patron.clase.nombre %>
	<span class="badge"><input type="number" value="<%= patron.duracion %>" min="1" max="999"></input> Día(s)</span>
	<a href="#" class="eliminar glyphicon glyphicon-trash" title="Eliminar"></a>
<% end %>

app/views/asignaturas/_form.html.erb
<%= form_for(@asignatura) do |f| %>
  <% if @asignatura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asignatura.errors.count, "error") %> han impedido que esta asignatura se guarde:</h2>

      <ul>
      <% @asignatura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table class="table panel panel-default">
    <tr>
      <td><strong><%= f.label :nombre%></strong></td>
        <td><%= f.text_field :nombre, class: "form-control" %></td>
    </tr>
    <tr>
      <td><strong><%= f.label :descripcion %></strong></td>
        <td><%= f.text_area :descripcion, class: "form-control" %></td>
    </tr>
    <tr>
      <td><strong><%= f.label :tags %></strong></td>
        <td><%= f.text_field :tags, class: "form-control", data: {role:"tagsinput"} %></td>
    </tr>
  </table>
  <div class="actions btn-group">
      <%= f.submit "Aceptar", class: "btn btn-primary" %>
      <%= link_to 'Inicio', asignaturas_path, class: "btn btn-default" %>
      <%= link_to 'Volver', @asignaturas, class: "btn btn-default" %>
  </div>
<% end %>

app/views/asignaturas/_modal_clase.html.erb
<% clases.each do |clase| %>
	<%= content_tag_for(:tr, clase) do %>
		<td><%= clase.nombre %></td>
		<td><%= clase.descripcion %></td>
		<td><%= clase.recursos %></td>
		<td>
			<% tags = clase.tags.split(",") %>
			<% tags.each do |tag| %>
				<span class="label label-info"><%= tag.strip %></span>
			<% end %>
		</td>
	<% end %>
<% end %>

app/views/asignaturas/_modal_nueva_clase.html.erb
<div id="nueva_clase" class="modal fade">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Cerrar</span>
        </button>
        <h4 class="modal-title">Selecciona una clase a añadir</h4>
      </div>
      <div class="modal-body">
        <%= render 'application/search_remote' %>
        <table class="table">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Descripción</th>
              <th>Recursos</th>
              <th>Tags</th>
            </tr>
          </thead>
          <tbody id="contenido_modal">
            <%= render partial: "modal_clase", locals: {clases: @clases} %>
          </tbody>
        </table>
        
      </div>
      <div class="modal-footer">
        <%= paginate @clases, :remote => true %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <%= button_to "Aceptar", {controller:"asignaturas", action: "nuevo_patron", id: "0"}, remote: true, method: :get, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/asignaturas/edit.html.erb
<h1>Editando asignatura</h1>
<p id="notice"><%= notice %></p>

<%= form_for(@asignatura) do |f| %>
	<% if @asignatura.errors.any? %>
		<div id="error_explanation">
		  <h2><%= pluralize(@asignatura.errors.count, "error") %> han impedido que esta asignatura se guarde:</h2>

		  <ul>
		  	<% @asignatura.errors.full_messages.each do |message| %>
		    	<li><%= message %></li>
		  	<% end %>
		  </ul>
		</div>
	<% end %>

	<table class="table panel panel-default">
		<tr>
			<td><strong><%= f.label :nombre%></strong></td>
	  		<td><%= f.text_field :nombre, class: "form-control" %></td>
		</tr>
		<tr>
			<td><strong><%= f.label :descripcion %></strong></td>
	  		<td><%= f.text_area :descripcion, class: "form-control" %></td>
		</tr>
		<tr>
			<td><strong><%= f.label :tags%></strong></td>
	  		<td><%= f.text_field :tags, class: "form-control", data: {role:"tagsinput"} %></td>
		</tr>
	</table>

	
		<p><strong>Clases de la asignatura:</strong></p>
		<ul class="list-group">
			<% if @asignatura.patron_clases.size != 0 %>
				<% @asignatura.patron_clases.order(:orden).each do |patron| %>
					<%= render "edicion_patron_clase", patron: patron %>
				<% end %>
			<% end %>
		</ul>
		<div class="panel panel-default">
  			<a href="#" data-toggle="modal" data-target="#nueva_clase"><div class="panel-body"><span class="glyphicon glyphicon-plus"></span> Añadir clase</div></a>
  		</div>

	<div class="actions btn-group">
	    <%= f.submit "Aceptar", class: "btn btn-primary" %>
	    <%= link_to 'Inicio', asignaturas_path, class: "btn btn-default" %>
	    <%= link_to 'Volver', @asignatura, class: "btn btn-default" %>
	</div>
<% end %>
<%= render "modal_nueva_clase" %>

app/views/asignaturas/edit.js.erb
<%# Plantilla para poblar el contenido del modal de inserción de nuevas clases en una asignatura %>
$('div#nueva_clase #contenido_modal').html('<%= escape_javascript(render partial: "modal_clase", locals: {clases: @clases}) %>');
$('div#nueva_clase .pagination').html('<%= escape_javascript(paginate(@clases, :remote => true).to_s) %>');
var nuevo = $(".modal-footer .button_to").attr("action").replace(/\d+/g,0);
$(".modal-footer .button_to").attr("action",nuevo);

app/views/asignaturas/index.html.erb
<h1>Listado de asignaturas</h1>
<br>
<%= link_to 'Nueva Asignatura', new_asignatura_path, class: "btn btn-default" %>
<br>
<%= render 'application/search' %>
<br>
<br>
<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Tags</th>
      <th>Opciones</th>
    </tr>
  </thead>

  <tbody>
    <%= render @asignaturas %>
  </tbody>
</table>

<%= paginate @asignaturas, :window => 2 %>

<br>

app/views/asignaturas/new.html.erb
<h1>Nueva asignatura</h1>

<%= render 'form' %>

app/views/asignaturas/nuevo_patron.js.erb
<% if @clase.to_i < 1 %>
	alert("Selecciona una opción.")
<% else %>
	$(".list-group").append('<%= escape_javascript(render "edicion_patron_clase") %>');
	$('#nueva_clase').modal('hide');
	$('.edit_asignatura .list-group').sortable('refresh');
<% end %>

app/views/asignaturas/show.html.erb
<table class="table panel panel-default">
	<tr>
		<td><strong>Nombre</strong></td>
  		<td><%= @asignatura.nombre %></td>
	</tr>
	<tr>
		<td><strong>Descripción</strong></td>
  		<td><%= @asignatura.descripcion %></td>
	</tr>
	<tr>
		<td><strong>Tags</strong></td>
  		<td><% tags = @asignatura.tags.split(",") %>
			<% tags.each do |tag| %>
			<%# Añadir link a búsqueda por ese tag %>
			<span class="label label-info"><%= tag.strip %></span>
			<% end %>
		</td>
	</tr>
</table>

<% if @asignatura.patron_clases.size != 0 %>
	<p><strong>Clases de la asignatura:</strong></p>
	<ul class="list-group">
		<% @asignatura.patron_clases.order(:orden).each do |patron| %>
			<%= content_tag_for(:li, patron, class: "list-group-item") do %>
				<%= link_to patron.clase.nombre, clase_path(patron.clase) %>
				<span class="badge"><%= pluralize(patron.duracion, "día") %></span>
			<% end %>
		<% end %>
	</ul>
<% end %>

<div class="btn-group">
<%= link_to 'Editar', edit_asignatura_path(@asignatura), class: "btn btn-default" %>
<%= link_to 'Inicio', asignaturas_path, class: "btn btn-default" %>
</div>