config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: { sessions: "usuarios/sessions" }

  root to: 'clases#index'
  resources :clases
  resources :asignaturas
  resources :patron_clases
  post 'patron_clases/edicion_multiple' => 'patron_clases#edicion_multiple'
  get 'asignaturas/nuevo_patron/:id' => 'asignaturas#nuevo_patron'
end

app/models/asignatura.rb
class Asignatura < ActiveRecord::Base
	has_many :patron_clases, dependent: :destroy
	has_many :clases, through: :patron_clases

	has_many :patron_asignaturas
	has_many :programas, through: :patron_asignaturas

	has_many :datos_calendarios
	has_many :calendarios, through: :datos_calendarios

	scope :search, ->(keyword){ where('keywords LIKE?',"%#{keyword.downcase}%") if keyword.present?}

	before_save :generar_keywords

	protected
		def generar_keywords
			self.keywords = [nombre,descripcion,tags].map(&:downcase).join(' ')
		end
end

app/models/calendario.rb
class Calendario < ActiveRecord::Base
	has_many :datos_calendarios
	has_many :asignaturas, through: :datos_calendarios

	has_many :clases, through: :datos_calendarios

	belongs_to :programa
	belongs_to :descanso
end

app/models/clase.rb
class Clase < ActiveRecord::Base
	has_many :patron_clases, dependent: :destroy
	has_many :asignaturas, through: :patron_clases

	has_many :datos_calendarios
	has_many :calendarios, through: :datos_calendarios

	scope :search, ->(keyword){ where('keywords LIKE?',"%#{keyword.downcase}%") if keyword.present?}

	before_save :generar_keywords

	protected
		def generar_keywords
			self.keywords = [nombre,descripcion,recursos,tags].map(&:downcase).join(' ')
		end
end

app/models/datos_calendario.rb
class DatosCalendario < ActiveRecord::Base
	belongs_to :asignatura
	belongs_to :calendario
	belongs_to :clase
end

app/models/descanso.rb
class Descanso < ActiveRecord::Base
	has_many :calendarios
	
	has_many :patron_descansos
	has_many :pausas, through: :patron_descansos
end

app/models/patron_asignatura.rb
class PatronAsignatura < ActiveRecord::Base
	belongs_to :asignatura
	belongs_to :programa
end

app/models/patron_clase.rb
class PatronClase < ActiveRecord::Base
	belongs_to :asignatura
	belongs_to :clase
end
#TODO: Revisar que la eliminación de asignaturas o clases destruya las relaciones existentes.

app/models/patron_descanso.rb
class PatronDescanso < ActiveRecord::Base
	belongs_to :descanso
	belongs_to :pausa
end

app/models/pausa.rb
class Pausa < ActiveRecord::Base
	has_many :patron_descansos
	has_many :descansos, through: :patron_descansos
end

app/models/programa.rb
class Programa < ActiveRecord::Base
	has_many :patron_asignaturas
	has_many :asignaturas, through: :patron_asignaturas

	has_many :calendarios
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/clases_controller.rb
# coding: utf-8
class ClasesController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_clase, only: [:show, :edit, :update, :destroy]

  # GET /clases
  # GET /clases.json
  def index
    @clases = Clase.search(params[:busqueda]).order(:nombre).page(params[:page]).per(30)
  end

  # GET /clases/1
  # GET /clases/1.json
  def show
  end

  # GET /clases/new
  def new
    @clase = Clase.new
  end

  # GET /clases/1/edit
  def edit
  end

  # POST /clases
  # POST /clases.json
  def create
    @clase = Clase.new(clase_params)

    respond_to do |format|
      if @clase.save
        format.html { redirect_to @clase, notice: 'La clase se ha creado con éxito.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /clases/1
  # PATCH/PUT /clases/1.json
  def update
    respond_to do |format|
      if @clase.update(clase_params)
        format.html { redirect_to @clase, notice: 'La clase se ha editado con éxito.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /clases/1
  # DELETE /clases/1.json
  def destroy
    @clase.destroy
    respond_to do |format|
      format.html { redirect_to clases_url, notice: 'La clase se ha eliminado con éxito.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clase
      @clase = Clase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clase_params
      params.require(:clase).permit(:nombre, :descripcion, :recursos, :tags)
    end
end

app/controllers/descansos_controller.rb
class DescansosController < ApplicationController
end

app/controllers/pausas_controller.rb
class PausasController < ApplicationController
end

app/controllers/programas_controller.rb
class ProgramasController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/helpers/calendarios_helper.rb
module CalendariosHelper
end

app/helpers/clases_helper.rb
module ClasesHelper
end

app/helpers/descansos_helper.rb
module DescansosHelper
end

app/helpers/pausas_helper.rb
module PausasHelper
end

app/helpers/programas_helper.rb
module ProgramasHelper
end

app/views/clases/_clase.html.erb
<%= content_tag_for(:tr, clase) do %>
	<td><%= link_to clase.nombre, clase %></td>
	<td><%= clase.descripcion %></td>
	<td><%= clase.recursos %></td>
	<td><% tags = clase.tags.split(",") %>
		<% tags.each do |tag| %>
		<%# Añadir link a búsqueda por ese tag %>
		<span class="label label-info"><%= tag.strip %></span>
		<% end %>
	</td>
<td><%= link_to '', edit_clase_path(clase), class: "glyphicon glyphicon-cog", title: "Editar" %>
		<%= link_to '', clase, method: :delete, data: { confirm: '¿Estás seguro?' }, class: "glyphicon glyphicon-trash", title: "Eliminar" %>
<% end %>

app/views/clases/_form.html.erb
<%= form_for(@clase) do |f| %>
  <% if @clase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clase.errors.count, "error") %> han impedido que esta clase se guarde:</h2>

      <ul>
      <% @clase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table panel panel-default">
    <tr>
      <td><strong><%= f.label :nombre %></strong></td>
        <td><%= f.text_field :nombre, class: "form-control" %></td>
    </tr>
    <tr>
      <td><strong><%= f.label :descripcion %></strong></td>
        <td><%= f.text_area :descripcion, class: "form-control" %></td>
    </tr>
    <tr>
      <td><strong><%= f.label :recursos %></strong></td>
        <td><%= f.text_field :recursos, class: "form-control" %></td>
    </tr>
    <tr>
      <td><strong><%= f.label :tags %></strong></td>
        <td><%= f.text_field :tags, class: "form-control", data: {role:"tagsinput"} %></td>
    </tr>
  </table>

  <div class="actions btn-group">
      <%= f.submit "Aceptar", class: "btn btn-primary" %>
      <%= link_to 'Inicio', clases_path, class: "btn btn-default" %>
      <%= link_to 'Volver', @clase, class: "btn btn-default" %>
  </div>
<% end %>

app/views/clases/edit.html.erb
<h1>Editando clase</h1>

<%= render 'form' %>

app/views/clases/index.html.erb
<h1>Listado de clases</h1>
<br>
<%= link_to 'Nueva Clase', new_clase_path, class: "btn btn-default" %>
<br>
<%= render 'application/search' %>
<br>
<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Recursos</th>
      <th>Tags</th>
      <th>Opciones</th>
    </tr>
  </thead>

  <tbody>
    <%= render @clases %>
  </tbody>
</table>

<%= paginate @clases, :window => 2 %>

<br>

app/views/clases/new.html.erb
<h1>Nueva clase</h1>

<%= render 'form' %>

app/views/clases/show.html.erb
<table class="table panel panel-default">
	<tr>
		<td><strong>Nombre</strong></td>
  		<td><%= @clase.nombre %></td>
	</tr>
	<tr>
		<td><strong>Descripción</strong></td>
  		<td><%= @clase.descripcion %></td>
	</tr>
	<tr>
		<td><strong>Recursos</strong></td>
  		<td><%= @clase.recursos %></td>
	<tr>
	<tr>
		<td><strong>Tags</strong></td>
  		<td><% tags = @clase.tags.split(",") %>
			<% tags.each do |tag| %>
			<%# Añadir link a búsqueda por ese tag %>
			<span class="label label-info"><%= tag.strip %></span>
			<% end %>
		</td>
	</tr>
</table>

<% if @clase.asignaturas.size != 0 %>
<strong>Esta clase aparece en las asignaturas:</strong>
<ul>
	<% @clase.asignaturas.each do |asignatura| %>
		<%= content_tag_for(:li, asignatura) do %>
			<%= link_to asignatura.nombre, asignatura_path(asignatura) %>
		<% end %>
	<% end %>
</ul>
<% end %>

<div class="btn-group">
<%= link_to 'Editar', edit_clase_path(@clase), class: "btn btn-default" %>
<%= link_to 'Inicio', clases_path, class: "btn btn-default" %>
</div>