config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: { sessions: "usuarios/sessions" }

  root to: 'clases#index'
  resources :clases
  resources :asignaturas
  resources :patron_clases
  post 'patron_clases/edicion_multiple' => 'patron_clases#edicion_multiple'
  get 'asignaturas/nuevo_patron/:id' => 'asignaturas#nuevo_patron'
end

app/models/asignatura.rb
class Asignatura < ActiveRecord::Base
	has_many :patron_clases, dependent: :destroy
	has_many :clases, through: :patron_clases

	has_many :patron_asignaturas
	has_many :programas, through: :patron_asignaturas

	has_many :datos_calendarios
	has_many :calendarios, through: :datos_calendarios

	scope :search, ->(keyword){ where('keywords LIKE?',"%#{keyword.downcase}%") if keyword.present?}

	before_save :generar_keywords

	protected
		def generar_keywords
			self.keywords = [nombre,descripcion,tags].map(&:downcase).join(' ')
		end
end

app/models/calendario.rb
class Calendario < ActiveRecord::Base
	has_many :datos_calendarios
	has_many :asignaturas, through: :datos_calendarios

	has_many :clases, through: :datos_calendarios

	belongs_to :programa
	belongs_to :descanso
end

app/models/clase.rb
class Clase < ActiveRecord::Base
	has_many :patron_clases, dependent: :destroy
	has_many :asignaturas, through: :patron_clases

	has_many :datos_calendarios
	has_many :calendarios, through: :datos_calendarios

	scope :search, ->(keyword){ where('keywords LIKE?',"%#{keyword.downcase}%") if keyword.present?}

	before_save :generar_keywords

	protected
		def generar_keywords
			self.keywords = [nombre,descripcion,recursos,tags].map(&:downcase).join(' ')
		end
end

app/models/datos_calendario.rb
class DatosCalendario < ActiveRecord::Base
	belongs_to :asignatura
	belongs_to :calendario
	belongs_to :clase
end

app/models/descanso.rb
class Descanso < ActiveRecord::Base
	has_many :calendarios
	
	has_many :patron_descansos
	has_many :pausas, through: :patron_descansos
end

app/models/patron_asignatura.rb
class PatronAsignatura < ActiveRecord::Base
	belongs_to :asignatura
	belongs_to :programa
end

app/models/patron_clase.rb
class PatronClase < ActiveRecord::Base
	belongs_to :asignatura
	belongs_to :clase
end
#TODO: Revisar que la eliminación de asignaturas o clases destruya las relaciones existentes.

app/models/patron_descanso.rb
class PatronDescanso < ActiveRecord::Base
	belongs_to :descanso
	belongs_to :pausa
end

app/models/pausa.rb
class Pausa < ActiveRecord::Base
	has_many :patron_descansos
	has_many :descansos, through: :patron_descansos
end

app/models/programa.rb
class Programa < ActiveRecord::Base
	has_many :patron_asignaturas
	has_many :asignaturas, through: :patron_asignaturas

	has_many :calendarios
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/clases_controller.rb
# coding: utf-8
class ClasesController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_clase, only: [:show, :edit, :update, :destroy]

  # GET /clases
  # GET /clases.json
  def index
    @clases = Clase.search(params[:busqueda]).order(:nombre).page(params[:page]).per(30)
  end

  # GET /clases/1
  # GET /clases/1.json
  def show
  end

  # GET /clases/new
  def new
    @clase = Clase.new
  end

  # GET /clases/1/edit
  def edit
  end

  # POST /clases
  # POST /clases.json
  def create
    @clase = Clase.new(clase_params)

    respond_to do |format|
      if @clase.save
        format.html { redirect_to @clase, notice: 'La clase se ha creado con éxito.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /clases/1
  # PATCH/PUT /clases/1.json
  def update
    respond_to do |format|
      if @clase.update(clase_params)
        format.html { redirect_to @clase, notice: 'La clase se ha editado con éxito.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /clases/1
  # DELETE /clases/1.json
  def destroy
    @clase.destroy
    respond_to do |format|
      format.html { redirect_to clases_url, notice: 'La clase se ha eliminado con éxito.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clase
      @clase = Clase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clase_params
      params.require(:clase).permit(:nombre, :descripcion, :recursos, :tags)
    end
end

app/controllers/pausas_controller.rb
class PausasController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/helpers/calendarios_helper.rb
module CalendariosHelper
end

app/helpers/clases_helper.rb
module ClasesHelper
end

app/helpers/descansos_helper.rb
module DescansosHelper
end

app/helpers/pausas_helper.rb
module PausasHelper
end

app/helpers/programas_helper.rb
module ProgramasHelper
end

app/views/layouts/_user_widget.html.erb
<% if usuario_signed_in? %>
	<li class="dropdown">
	  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_usuario.email %><span class="caret"></span></a>
	  <ul class="dropdown-menu" role="menu">
	    <li><a href="#">Mi perfil</a></li>
	    <li><a href="#">Opción 2</a></li>
	    <li class="divider"></li>
	    <li><%= link_to 'Cerrar sesión', destroy_usuario_session_path, :method => :delete %></li>
	  </ul>
	</li>
<% else %>
	<form class="navbar-form navbar-left" action="<%= url_for new_usuario_session_path %>">
	  <button type="submit" class="btn btn-default">Iniciar sesión</button>
	</form>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalendariosWeb</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div>
	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
			<ul class="nav navbar-nav">
				<li><%= link_to "Clases", clases_path %></li>
				<li><%= link_to "Asignaturas", asignaturas_path %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<%= render 'layouts/user_widget' %>
			</ul>
		</div>
	</nav>
	<% if flash[:alert] %>
		<div class="alert alert-danger alert-dismissible fade in" role="alert">
			<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<%= flash[:alert] %>
		</div>
	<% end %>
	<% if flash[:notice] %>
		<div class="alert alert-info alert-dismissible fade in" role="alert">
			<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
			<%= flash[:notice] %>
		</div>
	<% end %>
</div>
<div id="contenido">
	<%= yield %>
</div>
</body>
</html>